{
  "comments": [
    {
      "key": {
        "uuid": "1a76adc5_cc018e6b",
        "filename": "kubernetes/portal/charts/portal-cassandra/resources/config/cassandra/docker-entrypoint-initdb.d/portal.cql",
        "patchSetId": 8
      },
      "lineNbr": 13,
      "author": {
        "id": 131
      },
      "writtenOn": "2018-08-30T13:44:04Z",
      "side": 1,
      "message": "I don\u0027t think # is a valid comment character for cql...",
      "range": {
        "startLine": 1,
        "startChar": 1,
        "endLine": 13,
        "endChar": 32
      },
      "revId": "2a31ac2adde9cd96b476124e968cb79e60283c7f",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a76adc5_4c71fe42",
        "filename": "kubernetes/portal/charts/portal-cassandra/resources/config/cassandra/docker-entrypoint-initdb.d/portalsdk.cql",
        "patchSetId": 8
      },
      "lineNbr": 13,
      "author": {
        "id": 131
      },
      "writtenOn": "2018-08-30T13:44:04Z",
      "side": 1,
      "message": "According to https://docs.datastax.com/en/cql/3.1/cql/cql_reference/cqlRefComment.html\n\nA hash is not a valid comment character for cql files...\nDid you test that this file is correctly processed by the cassandra boot process?",
      "range": {
        "startLine": 1,
        "startChar": 0,
        "endLine": 13,
        "endChar": 32
      },
      "revId": "2a31ac2adde9cd96b476124e968cb79e60283c7f",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a76adc5_0ce546dc",
        "filename": "kubernetes/sdc/charts/sdc-wfd-be/templates/service.yaml",
        "patchSetId": 8
      },
      "lineNbr": 6,
      "author": {
        "id": 131
      },
      "writtenOn": "2018-08-30T13:44:04Z",
      "side": 1,
      "message": "please resolve this merge conflict",
      "range": {
        "startLine": 1,
        "startChar": 0,
        "endLine": 6,
        "endChar": 85
      },
      "revId": "2a31ac2adde9cd96b476124e968cb79e60283c7f",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a76adc5_ec06ca85",
        "filename": "kubernetes/sdnc/resources/geo/bin/sdnc.failover",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 131
      },
      "writtenOn": "2018-08-30T13:44:04Z",
      "side": 1,
      "message": "What is happening here?  It seems like your patch is adding this whole file back when perhaps it was purposefully removed?  please check again.",
      "revId": "2a31ac2adde9cd96b476124e968cb79e60283c7f",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    }
  ]
}